### ISSUE TITLE
bwait command failed

### ISSUE THREAD

**Issue by adamdingliang** [jyyulab/SJARACNe#14]
[20:52:44.975] INFO  - Fill out commands in the script /home/lding/cwl-workdir/29ca9a8a-2a88-49a6-a57c-829fe06fa645/consensus/consensus:
create_consensus_network.py -a /home/lding/cwl-workdir/29ca9a8a-2a88-49a6-a57c-829fe06fa645/copy_to_dir/results -p 1.0E-5 -e /home/lding/cwl-workdir/29ca9a8a-2a88-49a6-a57c-829fe06fa645/ch_ending_exp/BRCA100.exp -o results
[20:52:44.977] INFO  - Resuming job (consensus) <83971060> with
bresume \
83971060
[20:52:44.997] INFO  - Started to wait for jobs by
bwait \
-w \
done(83971060)
[20:54:09.231] ERROR - The bwait command failed to execute (exitCode=2, exitMsg=done(83971060): Wait condition is never satisfied)
[20:54:09.231] ERROR - The workflow (sjaracne_workflow) exited with <1>.
Traceback (most recent call last):
  File "/home/lding/.conda/envs/py361/bin/sjaracne", line 11, in <module>
    load_entry_point('SJARACNe==0.2.0', 'console_scripts', 'sjaracne')()
  File "/home/lding/.conda/envs/py361/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/sjaracne.py", line 101, in main
    run_shell_command_call(cmd)
  File "/home/lding/.conda/envs/py361/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/sjaracne.py", line 112, in run_shell_command_call
    subprocess.check_call(cmd_to_exec)
  File "/home/lding/.conda/envs/py361/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cwlexec', '-pe', 'PATH', '-c', './SJARACNe/config/config_cwlexec.json', '--outdir', './results', '/research/rgs01/home/clusterHome/lding/.conda/envs/py361/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/cwl/sjaracne_workflow.cwl', '/lsf_tmp/83967764.tmpdir/tmps27jpac_/sjaracne_workflow.yml']' returned non-zero exit status 1.

**Comment by adamdingliang** [comment]
This is due to incorrect step names in cwlexec configuration file. The resource requirement is not functional if the step names are wrong. Fixed.
