### ISSUE TITLE
problem to run sjaracne

### ISSUE THREAD

**Issue by ERIGR** [jyyulab/SJARACNe#24]
Hi,

I'm bioinformatician at the Gustave Roussy Institue in france and I want to try building new networks with SJ-ARACNE. To install J-ARACNE, I followed the method used in your readme file. So I install a conda environment called py36. Then I install numpy, scipy, pandas and cwltool using the requirements.txt file. I used the command pip install SJARACNe to install SJARACNe. Then, trying to use SJARACNE, I got the following error message : 
Traceback (most recent call last):
  File "/home/esteve/anaconda2/envs/py36/bin/sjaracne", line 11, in <module>
    load_entry_point('SJARACNe==0.2.0', 'console_scripts', 'sjaracne')()
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2855, in load_entry_point
    return ep.load()
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2446, in load
    return self.resolve()
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2452, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/__init__.py", line 1, in <module>
    from .bin import *
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/bin/__init__.py", line 2, in <module>
    from .create_consensus_network import *
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/bin/create_consensus_network.py", line 11, in <module>
    from scipy import stats
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/scipy-1.0.1-py3.6-linux-x86_64.egg/scipy/stats/__init__.py", line 345, in <module>
    from .morestats import *
  File "/home/esteve/anaconda2/envs/py36/lib/python3.6/site-packages/scipy-1.0.1-py3.6-linux-x86_64.egg/scipy/stats/morestats.py", line 12, in <module>
    from numpy.testing.decorators import setastest
ModuleNotFoundError: No module named 'numpy.testing.decorators'

What could be the problem ?
Thank you.

**Comment by adamdingliang** [comment]
numpy.testing.decorators is deprecated since numpy 1.15.0. See the following post: https://github.com/numpy/numpy/issues/12599

While we are working on resolving this for the future versions of numpy, installing an older version (specified in the requirements.txt file) is recommended.
